name: Deploy Terraform

on:
  push:
    branches:
      - main  # El workflow se ejecutará en push a la rama main

jobs:
  terraform:
    runs-on: ubuntu-latest  # Sistema operativo del runner

    env:
      AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
      AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
      # Agrega más variables de entorno si son necesarias

    steps:
      - name: Checkout code
        uses: actions/checkout@v3  # Acción para clonar el código del repositorio

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v1
        with:
          terraform_version: '1.2.0'  # Especifica la versión de Terraform que deseas usar

      - name: Terraform Init
        run: terraform init

      - name: Terraform Validate
        run: terraform validate

      - name: Terraform Plan
        run: terraform plan

      - name: Terraform Apply
        run: terraform apply -auto-approve
        # El flag -auto-approve permite aplicar los cambios sin intervención manual

